// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TestProject.Infrastructure;

#nullable disable

namespace TestProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0");

            // MongoDB collections will be created automatically by the MongoDB EF Core provider
            // based on the entity configurations in ApplicationDbContext
#pragma warning restore 612, 618
        }
    }
}
