# Generate migration scripts for all database + dotnet version combinations
# Output to template/src/ABC.Template.Infrastructure/MigrationsAll/Database-Framework directories

$ErrorActionPreference = "Stop"
$TEMPLATE_ROOT = $PSScriptRoot | Split-Path -Parent
$INFRA_MIGRATIONS_PATH = Join-Path $TEMPLATE_ROOT "template\src\ABC.Template.Infrastructure\MigrationsAll"
$TMP_ROOT = Join-Path $env:TEMP "netcorepal-migrations-$(New-Guid)"

# Database types
$DATABASES = @("MySql", "SqlServer", "PostgreSQL", "Sqlite", "GaussDB", "DMDB")
# Dotnet versions - check which SDKs are installed
$ALL_FRAMEWORKS = @("net8.0", "net9.0", "net10.0")
$INSTALLED_SDKS = dotnet --list-sdks | ForEach-Object { if ($_ -match '(\d+\.\d+\.\d+)') { $matches[1] } }
$FRAMEWORKS = @()
foreach ($fw in $ALL_FRAMEWORKS) {
    $sdkVersion = if ($fw -eq "net8.0") { "8.0" } elseif ($fw -eq "net9.0") { "9.0" } else { "10.0" }
    $hasSdk = $INSTALLED_SDKS | Where-Object { $_.StartsWith($sdkVersion) }
    if ($hasSdk) {
        $FRAMEWORKS += $fw
        Write-Host "Found SDK for $fw, will generate migrations"
    } else {
        Write-Host "Warning: SDK for $fw not found, skipping"
    }
}
if ($FRAMEWORKS.Count -eq 0) {
    Write-Host "Error: No compatible SDKs found. Please install .NET 8.0, 9.0, or 10.0 SDK."
    exit 1
}

# 1. Clear MigrationsAll directory before generation
Write-Host "==> Clearing $INFRA_MIGRATIONS_PATH ..."
if (Test-Path $INFRA_MIGRATIONS_PATH) {
    Remove-Item -Recurse -Force $INFRA_MIGRATIONS_PATH
}
New-Item -ItemType Directory -Path $INFRA_MIGRATIONS_PATH -Force | Out-Null

$MIGRATION_NAME = "Init"

# Generate migrations for both UseAdmin=true and UseAdmin=false
$USE_ADMIN_VALUES = @($false, $true)

foreach ($db in $DATABASES) {
    foreach ($fw in $FRAMEWORKS) {
        foreach ($useAdmin in $USE_ADMIN_VALUES) {
            $adminSuffix = if ($useAdmin) { "-admin" } else { "" }
            $PRJ_DIR = Join-Path $TMP_ROOT "${db}-${fw}${adminSuffix}"
            $OUTDIR = Join-Path $INFRA_MIGRATIONS_PATH "${db}-${fw}${adminSuffix}"
            
            Write-Host "==> Cleaning $PRJ_DIR ..."
            if (Test-Path $PRJ_DIR) {
                Remove-Item -Recurse -Force $PRJ_DIR
            }
            
            $adminParam = if ($useAdmin) { "--UseAdmin true" } else { "" }
            Write-Host "==> Generating $db $fw project with UseAdmin=$useAdmin..."
            if ($useAdmin) {
                dotnet new netcorepal-web -n ABC.Template -F $fw -D $db -M RabbitMQ --UseAdmin true --output $PRJ_DIR
            } else {
                dotnet new netcorepal-web -n ABC.Template -F $fw -D $db -M RabbitMQ --output $PRJ_DIR
            }
            
            $INFRA_DIR = Join-Path $PRJ_DIR "src\ABC.Template.Infrastructure"
            
            # Recursively clean the Migrations directory generated by dotnet new to avoid template pollution
            $MIGRATIONS_DIR = Join-Path $INFRA_DIR "Migrations"
            if (Test-Path $MIGRATIONS_DIR) {
                Remove-Item -Recurse -Force $MIGRATIONS_DIR
            }
            
            Write-Host "==> Running dotnet restore..."
            Push-Location $PRJ_DIR
            try {
                dotnet restore --ignore-failed-sources
            } finally {
                Pop-Location
            }
            
            Write-Host "==> Running dotnet build..."
            Push-Location $PRJ_DIR
            try {
                dotnet build --no-restore
            } finally {
                Pop-Location
            }
            
            Write-Host "==> Cleaning target migration directory..."
            if (Test-Path $OUTDIR) {
                Remove-Item -Recurse -Force $OUTDIR
            }
            
            Write-Host "==> Generating migration $MIGRATION_NAME..."
            Push-Location $INFRA_DIR
            try {
                dotnet ef migrations add $MIGRATION_NAME --output-dir Migrations
            } finally {
                Pop-Location
            }
            
            New-Item -ItemType Directory -Path $OUTDIR -Force | Out-Null
            $GENERATED_MIGRATIONS = Join-Path $INFRA_DIR "Migrations"
            Copy-Item -Path "$GENERATED_MIGRATIONS\*" -Destination $OUTDIR -Recurse -Force
            Write-Host "==> $db $fw UseAdmin=$useAdmin migration copied to $OUTDIR"
        }
    }
}

Write-Host "==> Cleaning temporary directory..."
if (Test-Path $TMP_ROOT) {
    Remove-Item -Recurse -Force $TMP_ROOT
}
Write-Host "All migrations generated successfully!"
