// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TestProject.Infrastructure;

#nullable disable

namespace TestProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0");

            // Entity configurations in ApplicationDbContext define MongoDB collection structure
            // Collections are created automatically when accessed with proper entity mappings
#pragma warning restore 612, 618
        }
    }
}
