name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore NetCorePal.Template.csproj
    - name: Build
      run: dotnet build --no-restore NetCorePal.Template.csproj
    - name: Test template syntax
      run: dotnet new netcorepal-web --help
    - name: Pack NuGet
      run: dotnet pack -c Release --version-suffix alpha`date +%y%m%d%H%M` -o "./" NetCorePal.Template.csproj 
    - name: Push NuGet
      run: dotnet nuget push '*.nupkg' -s https://www.myget.org/F/netcorepal/api/v3/index.json -k ${{ secrets.MYGET_API_KEY }} --skip-duplicate

  template-smoke-test:
    needs: build
    uses: ./.github/workflows/template-test.yml
    with:
      test-matrix: |
        [
          {
            "name": "Default-MySql-RabbitMQ",
            "framework": "net9.0",
            "database": "MySql",
            "messagequeue": "RabbitMQ"
          },
          {
            "name": "SqlServer-Kafka",
            "framework": "net8.0",
            "database": "SqlServer",
            "messagequeue": "Kafka"
          }
        ]
      include-docker-build: false
      include-tests: false
