name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore NetCorePal.Template.csproj
    - name: Build
      run: dotnet build --no-restore NetCorePal.Template.csproj
    - name: Test template syntax
      run: dotnet new netcorepal-web --help

  template-test:
    needs: build
    uses: ./.github/workflows/template-test.yml
    with:
      include-docker-build: true
      include-tests: true
