name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore NetCorePal.Template.csproj
    - name: Build
      run: dotnet build --no-restore NetCorePal.Template.csproj
    - name: Test template syntax
      run: dotnet new netcorepal-web --help

  template-test:
    needs: build
    uses: ./.github/workflows/template-test.yml
    with:
      test-matrix: |
        [
          {
            "name": "MySQL-RabbitMQ-NET8",
            "framework": "net8.0",
            "database": "MySql",
            "messagequeue": "RabbitMQ"
          },
          {
            "name": "SqlServer-Kafka-NET9",
            "framework": "net9.0",
            "database": "SqlServer",
            "messagequeue": "Kafka"
          },
          {
            "name": "PostgreSQL-RedisStreams-NET8",
            "framework": "net8.0",
            "database": "PostgreSQL",
            "messagequeue": "RedisStreams"
          },
          {
            "name": "MySqlOfficial-AzureServiceBus-NET9",
            "framework": "net9.0",
            "database": "MySqlOfficial",
            "messagequeue": "AzureServiceBus"
          },
          {
            "name": "Default-Configuration",
            "framework": "net9.0",
            "database": "MySql",
            "messagequeue": "RabbitMQ"
          }
        ]
      include-docker-build: false
      include-tests: false
